name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python (for uv compatibility)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or whatever version you use

      - name: Install dev dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest
