name: Tests

on:
  pull_request:  # ← triggers on all pull/merge requests into any branch
  push:
    branches: ["**"]  # optional: run on every push to any branch


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [debian-11, debian-12]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python (for uv compatibility)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # or whatever version you use

      - name: Install dev dependencies
        run: uv sync --dev

      - name: Run tests
        run: uv run pytest
